name: flask
channels:
  - conda-forge
  - defaults
dependencies:
  - aniso8601=8.0.0
  - appnope=0.1.0
  - asn1crypto=1.2.0
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - cffi=1.13.0
  - click=7.0
  - cryptography=2.7
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - flask=1.1.1
  - flask-restful=0.3.7
  - freetype=2.10.0
  - idna=2.8
  - importlib_metadata=0.23
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - itsdangerous=1.1.0
  - jedi=0.15.1
  - jinja2=2.10.3
  - joblib=0.14.0
  - jsonschema=3.1.1
  - jupyter_client=5.3.3
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libcxxabi=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - llvm-openmp=9.0.0
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - pandas=0.25.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyrsistent=0.15.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-dotenv=0.10.3
  - pytz=2019.3
  - pyzmq=18.1.0
  - readline=8.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - flask-jwt==0.3.2
    - flask-sqlalchemy==2.4.1
    - jwt==0.6.1
    - pycparser==2.19
    - pyjwt==1.4.2
    - sqlalchemy==1.3.10

